//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.AtmosphereService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bp.zjugis.edu", ConfigurationName="AtmosphereService.AtmosphereServicePortType")]
    public interface AtmosphereServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getZDMC", ReplyAction="urn:getZDMCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.AtmosphereService.getZDMCResponse getZDMC(QRST_DI_MS_Console.AtmosphereService.getZDMCRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getQueryAtmospheres", ReplyAction="urn:getQueryAtmospheresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresResponse getQueryAtmospheres(QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getZDBH", ReplyAction="urn:getZDBHResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.AtmosphereService.getZDBHResponse getZDBH(QRST_DI_MS_Console.AtmosphereService.getZDBHRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZDMC", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getZDMCRequest {
        
        public getZDMCRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZDMCResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getZDMCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getZDMCResponse() {
        }
        
        public getZDMCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryAtmospheres", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryAtmospheresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zdmc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zdbh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagenum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagesize;
        
        public getQueryAtmospheresRequest() {
        }
        
        public getQueryAtmospheresRequest(string maxLat, string maxLng, string minLat, string minLng, string zdmc, string zdbh, string pagenum, string pagesize) {
            this.maxLat = maxLat;
            this.maxLng = maxLng;
            this.minLat = minLat;
            this.minLng = minLng;
            this.zdmc = zdmc;
            this.zdbh = zdbh;
            this.pagenum = pagenum;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryAtmospheresResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryAtmospheresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getQueryAtmospheresResponse() {
        }
        
        public getQueryAtmospheresResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZDBH", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getZDBHRequest {
        
        public getZDBHRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getZDBHResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getZDBHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getZDBHResponse() {
        }
        
        public getZDBHResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AtmosphereServicePortTypeChannel : QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtmosphereServicePortTypeClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType>, QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType {
        
        public AtmosphereServicePortTypeClient() {
        }
        
        public AtmosphereServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtmosphereServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmosphereServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmosphereServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.AtmosphereService.getZDMCResponse QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType.getZDMC(QRST_DI_MS_Console.AtmosphereService.getZDMCRequest request) {
            return base.Channel.getZDMC(request);
        }
        
        public string getZDMC() {
            QRST_DI_MS_Console.AtmosphereService.getZDMCRequest inValue = new QRST_DI_MS_Console.AtmosphereService.getZDMCRequest();
            QRST_DI_MS_Console.AtmosphereService.getZDMCResponse retVal = ((QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType)(this)).getZDMC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresResponse QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType.getQueryAtmospheres(QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresRequest request) {
            return base.Channel.getQueryAtmospheres(request);
        }
        
        public string getQueryAtmospheres(string maxLat, string maxLng, string minLat, string minLng, string zdmc, string zdbh, string pagenum, string pagesize) {
            QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresRequest inValue = new QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresRequest();
            inValue.maxLat = maxLat;
            inValue.maxLng = maxLng;
            inValue.minLat = minLat;
            inValue.minLng = minLng;
            inValue.zdmc = zdmc;
            inValue.zdbh = zdbh;
            inValue.pagenum = pagenum;
            inValue.pagesize = pagesize;
            QRST_DI_MS_Console.AtmosphereService.getQueryAtmospheresResponse retVal = ((QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType)(this)).getQueryAtmospheres(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.AtmosphereService.getZDBHResponse QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType.getZDBH(QRST_DI_MS_Console.AtmosphereService.getZDBHRequest request) {
            return base.Channel.getZDBH(request);
        }
        
        public string getZDBH() {
            QRST_DI_MS_Console.AtmosphereService.getZDBHRequest inValue = new QRST_DI_MS_Console.AtmosphereService.getZDBHRequest();
            QRST_DI_MS_Console.AtmosphereService.getZDBHResponse retVal = ((QRST_DI_MS_Console.AtmosphereService.AtmosphereServicePortType)(this)).getZDBH(inValue);
            return retVal.@return;
        }
    }
}
