//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.NMInfoService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gis.zju/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gis.zju/", ConfigurationName="NMInfoService.NMInfoDelegate")]
    public interface NMInfoDelegate {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.NMInfoService.getcpuPercResponse getcpuPerc(QRST_DI_MS_Console.NMInfoService.getcpuPercRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryResponse getPhysicalMemory(QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(QRST_DI_MS_Console.NMInfoService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.NMInfoService.getDiskUsageResponse getDiskUsage(QRST_DI_MS_Console.NMInfoService.getDiskUsageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcpuPerc", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getcpuPercRequest {
        
        public getcpuPercRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcpuPercResponse", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getcpuPercResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gis.zju/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getcpuPercResponse() {
        }
        
        public getcpuPercResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPhysicalMemory", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getPhysicalMemoryRequest {
        
        public getPhysicalMemoryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPhysicalMemoryResponse", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getPhysicalMemoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gis.zju/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getPhysicalMemoryResponse() {
        }
        
        public getPhysicalMemoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDiskUsage", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getDiskUsageRequest {
        
        public getDiskUsageRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDiskUsageResponse", WrapperNamespace="http://gis.zju/", IsWrapped=true)]
    public partial class getDiskUsageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gis.zju/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getDiskUsageResponse() {
        }
        
        public getDiskUsageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NMInfoDelegateChannel : QRST_DI_MS_Console.NMInfoService.NMInfoDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NMInfoDelegateClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.NMInfoService.NMInfoDelegate>, QRST_DI_MS_Console.NMInfoService.NMInfoDelegate {
        
        public NMInfoDelegateClient() {
        }
        
        public NMInfoDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NMInfoDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NMInfoDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NMInfoDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.NMInfoService.getcpuPercResponse QRST_DI_MS_Console.NMInfoService.NMInfoDelegate.getcpuPerc(QRST_DI_MS_Console.NMInfoService.getcpuPercRequest request) {
            return base.Channel.getcpuPerc(request);
        }
        
        public string getcpuPerc() {
            QRST_DI_MS_Console.NMInfoService.getcpuPercRequest inValue = new QRST_DI_MS_Console.NMInfoService.getcpuPercRequest();
            QRST_DI_MS_Console.NMInfoService.getcpuPercResponse retVal = ((QRST_DI_MS_Console.NMInfoService.NMInfoDelegate)(this)).getcpuPerc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryResponse QRST_DI_MS_Console.NMInfoService.NMInfoDelegate.getPhysicalMemory(QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryRequest request) {
            return base.Channel.getPhysicalMemory(request);
        }
        
        public string getPhysicalMemory() {
            QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryRequest inValue = new QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryRequest();
            QRST_DI_MS_Console.NMInfoService.getPhysicalMemoryResponse retVal = ((QRST_DI_MS_Console.NMInfoService.NMInfoDelegate)(this)).getPhysicalMemory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.NMInfoService.getDiskUsageResponse QRST_DI_MS_Console.NMInfoService.NMInfoDelegate.getDiskUsage(QRST_DI_MS_Console.NMInfoService.getDiskUsageRequest request) {
            return base.Channel.getDiskUsage(request);
        }
        
        public string getDiskUsage() {
            QRST_DI_MS_Console.NMInfoService.getDiskUsageRequest inValue = new QRST_DI_MS_Console.NMInfoService.getDiskUsageRequest();
            QRST_DI_MS_Console.NMInfoService.getDiskUsageResponse retVal = ((QRST_DI_MS_Console.NMInfoService.NMInfoDelegate)(this)).getDiskUsage(inValue);
            return retVal.@return;
        }
    }
}
