//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1022 版自动生成。
// 
#pragma warning disable 1591

namespace QRST_DI_MS_Console.WS_QDB_GetDataService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRalativeAddByDataCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCorrectedDataAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTilesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSourceDataPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::QRST_DI_MS_Console.Properties.Settings.Default.QRST_DI_MS_Console_WS_QDB_GetDataService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetRalativeAddByDataCodeCompletedEventHandler GetRalativeAddByDataCodeCompleted;
        
        /// <remarks/>
        public event GetAddressFieldsCompletedEventHandler GetAddressFieldsCompleted;
        
        /// <remarks/>
        public event GetCorrectedDataAddressCompletedEventHandler GetCorrectedDataAddressCompleted;
        
        /// <remarks/>
        public event GetTilesListCompletedEventHandler GetTilesListCompleted;
        
        /// <remarks/>
        public event GetSourceDataPathCompletedEventHandler GetSourceDataPathCompleted;
        
        /// <remarks/>
        public event DeleteDataCompletedEventHandler DeleteDataCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRalativeAddByDataCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRalativeAddByDataCode(string dataCode) {
            object[] results = this.Invoke("GetRalativeAddByDataCode", new object[] {
                        dataCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRalativeAddByDataCodeAsync(string dataCode) {
            this.GetRalativeAddByDataCodeAsync(dataCode, null);
        }
        
        /// <remarks/>
        public void GetRalativeAddByDataCodeAsync(string dataCode, object userState) {
            if ((this.GetRalativeAddByDataCodeOperationCompleted == null)) {
                this.GetRalativeAddByDataCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRalativeAddByDataCodeOperationCompleted);
            }
            this.InvokeAsync("GetRalativeAddByDataCode", new object[] {
                        dataCode}, this.GetRalativeAddByDataCodeOperationCompleted, userState);
        }
        
        private void OnGetRalativeAddByDataCodeOperationCompleted(object arg) {
            if ((this.GetRalativeAddByDataCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRalativeAddByDataCodeCompleted(this, new GetRalativeAddByDataCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAddressFields", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAddressFields(string dataCode) {
            object[] results = this.Invoke("GetAddressFields", new object[] {
                        dataCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressFieldsAsync(string dataCode) {
            this.GetAddressFieldsAsync(dataCode, null);
        }
        
        /// <remarks/>
        public void GetAddressFieldsAsync(string dataCode, object userState) {
            if ((this.GetAddressFieldsOperationCompleted == null)) {
                this.GetAddressFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressFieldsOperationCompleted);
            }
            this.InvokeAsync("GetAddressFields", new object[] {
                        dataCode}, this.GetAddressFieldsOperationCompleted, userState);
        }
        
        private void OnGetAddressFieldsOperationCompleted(object arg) {
            if ((this.GetAddressFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressFieldsCompleted(this, new GetAddressFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCorrectedDataAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCorrectedDataAddress(string DataName) {
            object[] results = this.Invoke("GetCorrectedDataAddress", new object[] {
                        DataName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCorrectedDataAddressAsync(string DataName) {
            this.GetCorrectedDataAddressAsync(DataName, null);
        }
        
        /// <remarks/>
        public void GetCorrectedDataAddressAsync(string DataName, object userState) {
            if ((this.GetCorrectedDataAddressOperationCompleted == null)) {
                this.GetCorrectedDataAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCorrectedDataAddressOperationCompleted);
            }
            this.InvokeAsync("GetCorrectedDataAddress", new object[] {
                        DataName}, this.GetCorrectedDataAddressOperationCompleted, userState);
        }
        
        private void OnGetCorrectedDataAddressOperationCompleted(object arg) {
            if ((this.GetCorrectedDataAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCorrectedDataAddressCompleted(this, new GetCorrectedDataAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTilesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTilesList(string[] tileNames) {
            object[] results = this.Invoke("GetTilesList", new object[] {
                        tileNames});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTilesListAsync(string[] tileNames) {
            this.GetTilesListAsync(tileNames, null);
        }
        
        /// <remarks/>
        public void GetTilesListAsync(string[] tileNames, object userState) {
            if ((this.GetTilesListOperationCompleted == null)) {
                this.GetTilesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTilesListOperationCompleted);
            }
            this.InvokeAsync("GetTilesList", new object[] {
                        tileNames}, this.GetTilesListOperationCompleted, userState);
        }
        
        private void OnGetTilesListOperationCompleted(object arg) {
            if ((this.GetTilesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTilesListCompleted(this, new GetTilesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSourceDataPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSourceDataPath(string DataCode) {
            object[] results = this.Invoke("GetSourceDataPath", new object[] {
                        DataCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSourceDataPathAsync(string DataCode) {
            this.GetSourceDataPathAsync(DataCode, null);
        }
        
        /// <remarks/>
        public void GetSourceDataPathAsync(string DataCode, object userState) {
            if ((this.GetSourceDataPathOperationCompleted == null)) {
                this.GetSourceDataPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSourceDataPathOperationCompleted);
            }
            this.InvokeAsync("GetSourceDataPath", new object[] {
                        DataCode}, this.GetSourceDataPathOperationCompleted, userState);
        }
        
        private void OnGetSourceDataPathOperationCompleted(object arg) {
            if ((this.GetSourceDataPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSourceDataPathCompleted(this, new GetSourceDataPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteData(string datacode) {
            object[] results = this.Invoke("DeleteData", new object[] {
                        datacode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDataAsync(string datacode) {
            this.DeleteDataAsync(datacode, null);
        }
        
        /// <remarks/>
        public void DeleteDataAsync(string datacode, object userState) {
            if ((this.DeleteDataOperationCompleted == null)) {
                this.DeleteDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDataOperationCompleted);
            }
            this.InvokeAsync("DeleteData", new object[] {
                        datacode}, this.DeleteDataOperationCompleted, userState);
        }
        
        private void OnDeleteDataOperationCompleted(object arg) {
            if ((this.DeleteDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDataCompleted(this, new DeleteDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetData(string DataType, string QRST_CODE) {
            object[] results = this.Invoke("GetData", new object[] {
                        DataType,
                        QRST_CODE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string DataType, string QRST_CODE) {
            this.GetDataAsync(DataType, QRST_CODE, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string DataType, string QRST_CODE, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        DataType,
                        QRST_CODE}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRalativeAddByDataCodeCompletedEventHandler(object sender, GetRalativeAddByDataCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRalativeAddByDataCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRalativeAddByDataCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAddressFieldsCompletedEventHandler(object sender, GetAddressFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCorrectedDataAddressCompletedEventHandler(object sender, GetCorrectedDataAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCorrectedDataAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCorrectedDataAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTilesListCompletedEventHandler(object sender, GetTilesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTilesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTilesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSourceDataPathCompletedEventHandler(object sender, GetSourceDataPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSourceDataPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSourceDataPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteDataCompletedEventHandler(object sender, DeleteDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591