//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.WS_QDB_Searcher_MySQL {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_QDB_Searcher_MySQL.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTreeCatalogByXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTreeCatalogByXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFieldsByDataCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetFieldsByDataCode(string dataCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SerchMySQLDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SerchMySQLDB(LogicalOperator[] listLogicalOperators, SimpleCondition[] listSimpleConditions, string dataCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LogicalOperator {
        
        /// <remarks/>
        ANDto,
        
        /// <remarks/>
        ORto,
        
        /// <remarks/>
        NotDefine,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SimpleCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sC_VariableField;
        
        private FieldOperator sC_FieldOperatorField;
        
        private string sC_ValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SC_Variable {
            get {
                return this.sC_VariableField;
            }
            set {
                this.sC_VariableField = value;
                this.RaisePropertyChanged("SC_Variable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FieldOperator SC_FieldOperator {
            get {
                return this.sC_FieldOperatorField;
            }
            set {
                this.sC_FieldOperatorField = value;
                this.RaisePropertyChanged("SC_FieldOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SC_Value {
            get {
                return this.sC_ValueField;
            }
            set {
                this.sC_ValueField = value;
                this.RaisePropertyChanged("SC_Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum FieldOperator {
        
        /// <remarks/>
        Eto,
        
        /// <remarks/>
        NEto,
        
        /// <remarks/>
        Gto,
        
        /// <remarks/>
        GEto,
        
        /// <remarks/>
        Lto,
        
        /// <remarks/>
        LEto,
        
        /// <remarks/>
        Liketo,
        
        /// <remarks/>
        NLiketo,
        
        /// <remarks/>
        NotDefine,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QRST_DI_MS_Console.WS_QDB_Searcher_MySQL.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.WS_QDB_Searcher_MySQL.ServiceSoap>, QRST_DI_MS_Console.WS_QDB_Searcher_MySQL.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Xml.XmlNode GetTreeCatalogByXML() {
            return base.Channel.GetTreeCatalogByXML();
        }
        
        public string[] GetFieldsByDataCode(string dataCode) {
            return base.Channel.GetFieldsByDataCode(dataCode);
        }
        
        public System.Data.DataSet SerchMySQLDB(LogicalOperator[] listLogicalOperators, SimpleCondition[] listSimpleConditions, string dataCode) {
            return base.Channel.SerchMySQLDB(listLogicalOperators, listSimpleConditions, dataCode);
        }
    }
}
