//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.WS_QDB_GetData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_QDB_GetData.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldResponse HelloWorld(QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dataCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRalativeAddByDataCode", ReplyAction="*")]
        QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeResponse GetRalativeAddByDataCode(QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dataCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressFields", ReplyAction="*")]
        QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsResponse GetAddressFields(QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRalativeAddByDataCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRalativeAddByDataCode", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequestBody Body;
        
        public GetRalativeAddByDataCodeRequest() {
        }
        
        public GetRalativeAddByDataCodeRequest(QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRalativeAddByDataCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataCode;
        
        public GetRalativeAddByDataCodeRequestBody() {
        }
        
        public GetRalativeAddByDataCodeRequestBody(string dataCode) {
            this.dataCode = dataCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRalativeAddByDataCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRalativeAddByDataCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeResponseBody Body;
        
        public GetRalativeAddByDataCodeResponse() {
        }
        
        public GetRalativeAddByDataCodeResponse(QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRalativeAddByDataCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRalativeAddByDataCodeResult;
        
        public GetRalativeAddByDataCodeResponseBody() {
        }
        
        public GetRalativeAddByDataCodeResponseBody(string GetRalativeAddByDataCodeResult) {
            this.GetRalativeAddByDataCodeResult = GetRalativeAddByDataCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressFieldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressFields", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequestBody Body;
        
        public GetAddressFieldsRequest() {
        }
        
        public GetAddressFieldsRequest(QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressFieldsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataCode;
        
        public GetAddressFieldsRequestBody() {
        }
        
        public GetAddressFieldsRequestBody(string dataCode) {
            this.dataCode = dataCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressFieldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressFieldsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsResponseBody Body;
        
        public GetAddressFieldsResponse() {
        }
        
        public GetAddressFieldsResponse(QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressFieldsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QRST_DI_MS_Console.WS_QDB_GetData.ArrayOfString GetAddressFieldsResult;
        
        public GetAddressFieldsResponseBody() {
        }
        
        public GetAddressFieldsResponseBody(QRST_DI_MS_Console.WS_QDB_GetData.ArrayOfString GetAddressFieldsResult) {
            this.GetAddressFieldsResult = GetAddressFieldsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap>, QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldResponse QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap.HelloWorld(QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequest inValue = new QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequest();
            inValue.Body = new QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldRequestBody();
            QRST_DI_MS_Console.WS_QDB_GetData.HelloWorldResponse retVal = ((QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeResponse QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap.GetRalativeAddByDataCode(QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequest request) {
            return base.Channel.GetRalativeAddByDataCode(request);
        }
        
        public string GetRalativeAddByDataCode(string dataCode) {
            QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequest inValue = new QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequest();
            inValue.Body = new QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeRequestBody();
            inValue.Body.dataCode = dataCode;
            QRST_DI_MS_Console.WS_QDB_GetData.GetRalativeAddByDataCodeResponse retVal = ((QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap)(this)).GetRalativeAddByDataCode(inValue);
            return retVal.Body.GetRalativeAddByDataCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsResponse QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap.GetAddressFields(QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequest request) {
            return base.Channel.GetAddressFields(request);
        }
        
        public QRST_DI_MS_Console.WS_QDB_GetData.ArrayOfString GetAddressFields(string dataCode) {
            QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequest inValue = new QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequest();
            inValue.Body = new QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsRequestBody();
            inValue.Body.dataCode = dataCode;
            QRST_DI_MS_Console.WS_QDB_GetData.GetAddressFieldsResponse retVal = ((QRST_DI_MS_Console.WS_QDB_GetData.ServiceSoap)(this)).GetAddressFields(inValue);
            return retVal.Body.GetAddressFieldsResult;
        }
    }
}
