//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.WaterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bp.zjugis.edu", ConfigurationName="WaterService.WaterServicePortType")]
    public interface WaterServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSSLB", ReplyAction="urn:getSSLBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.WaterService.getSSLBResponse getSSLB(QRST_DI_MS_Console.WaterService.getSSLBRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getGPSJ", ReplyAction="urn:getGPSJResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.WaterService.getGPSJResponse getGPSJ(QRST_DI_MS_Console.WaterService.getGPSJRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getQueryWaters", ReplyAction="urn:getQueryWatersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.WaterService.getQueryWatersResponse getQueryWaters(QRST_DI_MS_Console.WaterService.getQueryWatersRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSYMC", ReplyAction="urn:getSYMCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.WaterService.getSYMCResponse getSYMC(QRST_DI_MS_Console.WaterService.getSYMCRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getGPYQ", ReplyAction="urn:getGPYQResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.WaterService.getGPYQResponse getGPYQ(QRST_DI_MS_Console.WaterService.getGPYQRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSSLB", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getSSLBRequest {
        
        public getSSLBRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSSLBResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getSSLBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getSSLBResponse() {
        }
        
        public getSSLBResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJ", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fseq;
        
        public getGPSJRequest() {
        }
        
        public getGPSJRequest(string fseq) {
            this.fseq = fseq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getGPSJResponse() {
        }
        
        public getGPSJResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryWaters", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryWatersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string symc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gpyq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sslb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagenum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagesize;
        
        public getQueryWatersRequest() {
        }
        
        public getQueryWatersRequest(string dts, string dte, string maxLat, string maxLng, string minLat, string minLng, string symc, string gpyq, string sslb, string pagenum, string pagesize) {
            this.dts = dts;
            this.dte = dte;
            this.maxLat = maxLat;
            this.maxLng = maxLng;
            this.minLat = minLat;
            this.minLng = minLng;
            this.symc = symc;
            this.gpyq = gpyq;
            this.sslb = sslb;
            this.pagenum = pagenum;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryWatersResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryWatersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getQueryWatersResponse() {
        }
        
        public getQueryWatersResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSYMC", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getSYMCRequest {
        
        public getSYMCRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSYMCResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getSYMCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getSYMCResponse() {
        }
        
        public getSYMCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPYQ", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPYQRequest {
        
        public getGPYQRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPYQResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPYQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getGPYQResponse() {
        }
        
        public getGPYQResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WaterServicePortTypeChannel : QRST_DI_MS_Console.WaterService.WaterServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaterServicePortTypeClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.WaterService.WaterServicePortType>, QRST_DI_MS_Console.WaterService.WaterServicePortType {
        
        public WaterServicePortTypeClient() {
        }
        
        public WaterServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaterServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WaterService.getSSLBResponse QRST_DI_MS_Console.WaterService.WaterServicePortType.getSSLB(QRST_DI_MS_Console.WaterService.getSSLBRequest request) {
            return base.Channel.getSSLB(request);
        }
        
        public string getSSLB() {
            QRST_DI_MS_Console.WaterService.getSSLBRequest inValue = new QRST_DI_MS_Console.WaterService.getSSLBRequest();
            QRST_DI_MS_Console.WaterService.getSSLBResponse retVal = ((QRST_DI_MS_Console.WaterService.WaterServicePortType)(this)).getSSLB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WaterService.getGPSJResponse QRST_DI_MS_Console.WaterService.WaterServicePortType.getGPSJ(QRST_DI_MS_Console.WaterService.getGPSJRequest request) {
            return base.Channel.getGPSJ(request);
        }
        
        public string getGPSJ(string fseq) {
            QRST_DI_MS_Console.WaterService.getGPSJRequest inValue = new QRST_DI_MS_Console.WaterService.getGPSJRequest();
            inValue.fseq = fseq;
            QRST_DI_MS_Console.WaterService.getGPSJResponse retVal = ((QRST_DI_MS_Console.WaterService.WaterServicePortType)(this)).getGPSJ(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WaterService.getQueryWatersResponse QRST_DI_MS_Console.WaterService.WaterServicePortType.getQueryWaters(QRST_DI_MS_Console.WaterService.getQueryWatersRequest request) {
            return base.Channel.getQueryWaters(request);
        }
        
        public string getQueryWaters(string dts, string dte, string maxLat, string maxLng, string minLat, string minLng, string symc, string gpyq, string sslb, string pagenum, string pagesize) {
            QRST_DI_MS_Console.WaterService.getQueryWatersRequest inValue = new QRST_DI_MS_Console.WaterService.getQueryWatersRequest();
            inValue.dts = dts;
            inValue.dte = dte;
            inValue.maxLat = maxLat;
            inValue.maxLng = maxLng;
            inValue.minLat = minLat;
            inValue.minLng = minLng;
            inValue.symc = symc;
            inValue.gpyq = gpyq;
            inValue.sslb = sslb;
            inValue.pagenum = pagenum;
            inValue.pagesize = pagesize;
            QRST_DI_MS_Console.WaterService.getQueryWatersResponse retVal = ((QRST_DI_MS_Console.WaterService.WaterServicePortType)(this)).getQueryWaters(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WaterService.getSYMCResponse QRST_DI_MS_Console.WaterService.WaterServicePortType.getSYMC(QRST_DI_MS_Console.WaterService.getSYMCRequest request) {
            return base.Channel.getSYMC(request);
        }
        
        public string getSYMC() {
            QRST_DI_MS_Console.WaterService.getSYMCRequest inValue = new QRST_DI_MS_Console.WaterService.getSYMCRequest();
            QRST_DI_MS_Console.WaterService.getSYMCResponse retVal = ((QRST_DI_MS_Console.WaterService.WaterServicePortType)(this)).getSYMC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.WaterService.getGPYQResponse QRST_DI_MS_Console.WaterService.WaterServicePortType.getGPYQ(QRST_DI_MS_Console.WaterService.getGPYQRequest request) {
            return base.Channel.getGPYQ(request);
        }
        
        public string getGPYQ() {
            QRST_DI_MS_Console.WaterService.getGPYQRequest inValue = new QRST_DI_MS_Console.WaterService.getGPYQRequest();
            QRST_DI_MS_Console.WaterService.getGPYQResponse retVal = ((QRST_DI_MS_Console.WaterService.WaterServicePortType)(this)).getGPYQ(inValue);
            return retVal.@return;
        }
    }
}
