//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.CityObjService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bp.zjugis.edu", ConfigurationName="CityObjService.CityObjServicePortType")]
    public interface CityObjServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getQueryCityObjs", ReplyAction="urn:getQueryCityObjsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.CityObjService.getQueryCityObjsResponse getQueryCityObjs(QRST_DI_MS_Console.CityObjService.getQueryCityObjsRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getGPSJ", ReplyAction="urn:getGPSJResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.CityObjService.getGPSJResponse getGPSJ(QRST_DI_MS_Console.CityObjService.getGPSJRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTypes", ReplyAction="urn:getTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.CityObjService.getTypesResponse getTypes(QRST_DI_MS_Console.CityObjService.getTypesRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCSMBMC", ReplyAction="urn:getCSMBMCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.CityObjService.getCSMBMCResponse getCSMBMC(QRST_DI_MS_Console.CityObjService.getCSMBMCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryCityObjs", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryCityObjsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string csmbmc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string csmblb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagenum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagesize;
        
        public getQueryCityObjsRequest() {
        }
        
        public getQueryCityObjsRequest(string dts, string dte, string csmbmc, string csmblb, string pagenum, string pagesize) {
            this.dts = dts;
            this.dte = dte;
            this.csmbmc = csmbmc;
            this.csmblb = csmblb;
            this.pagenum = pagenum;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryCityObjsResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryCityObjsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getQueryCityObjsResponse() {
        }
        
        public getQueryCityObjsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJ", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fseq;
        
        public getGPSJRequest() {
        }
        
        public getGPSJRequest(string fseq) {
            this.fseq = fseq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getGPSJResponse() {
        }
        
        public getGPSJResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypes", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getTypesRequest {
        
        public getTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypesResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getTypesResponse() {
        }
        
        public getTypesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCSMBMC", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getCSMBMCRequest {
        
        public getCSMBMCRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCSMBMCResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getCSMBMCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getCSMBMCResponse() {
        }
        
        public getCSMBMCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CityObjServicePortTypeChannel : QRST_DI_MS_Console.CityObjService.CityObjServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CityObjServicePortTypeClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.CityObjService.CityObjServicePortType>, QRST_DI_MS_Console.CityObjService.CityObjServicePortType {
        
        public CityObjServicePortTypeClient() {
        }
        
        public CityObjServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CityObjServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityObjServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityObjServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.CityObjService.getQueryCityObjsResponse QRST_DI_MS_Console.CityObjService.CityObjServicePortType.getQueryCityObjs(QRST_DI_MS_Console.CityObjService.getQueryCityObjsRequest request) {
            return base.Channel.getQueryCityObjs(request);
        }
        
        public string getQueryCityObjs(string dts, string dte, string csmbmc, string csmblb, string pagenum, string pagesize) {
            QRST_DI_MS_Console.CityObjService.getQueryCityObjsRequest inValue = new QRST_DI_MS_Console.CityObjService.getQueryCityObjsRequest();
            inValue.dts = dts;
            inValue.dte = dte;
            inValue.csmbmc = csmbmc;
            inValue.csmblb = csmblb;
            inValue.pagenum = pagenum;
            inValue.pagesize = pagesize;
            QRST_DI_MS_Console.CityObjService.getQueryCityObjsResponse retVal = ((QRST_DI_MS_Console.CityObjService.CityObjServicePortType)(this)).getQueryCityObjs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.CityObjService.getGPSJResponse QRST_DI_MS_Console.CityObjService.CityObjServicePortType.getGPSJ(QRST_DI_MS_Console.CityObjService.getGPSJRequest request) {
            return base.Channel.getGPSJ(request);
        }
        
        public string getGPSJ(string fseq) {
            QRST_DI_MS_Console.CityObjService.getGPSJRequest inValue = new QRST_DI_MS_Console.CityObjService.getGPSJRequest();
            inValue.fseq = fseq;
            QRST_DI_MS_Console.CityObjService.getGPSJResponse retVal = ((QRST_DI_MS_Console.CityObjService.CityObjServicePortType)(this)).getGPSJ(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.CityObjService.getTypesResponse QRST_DI_MS_Console.CityObjService.CityObjServicePortType.getTypes(QRST_DI_MS_Console.CityObjService.getTypesRequest request) {
            return base.Channel.getTypes(request);
        }
        
        public string getTypes() {
            QRST_DI_MS_Console.CityObjService.getTypesRequest inValue = new QRST_DI_MS_Console.CityObjService.getTypesRequest();
            QRST_DI_MS_Console.CityObjService.getTypesResponse retVal = ((QRST_DI_MS_Console.CityObjService.CityObjServicePortType)(this)).getTypes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.CityObjService.getCSMBMCResponse QRST_DI_MS_Console.CityObjService.CityObjServicePortType.getCSMBMC(QRST_DI_MS_Console.CityObjService.getCSMBMCRequest request) {
            return base.Channel.getCSMBMC(request);
        }
        
        public string getCSMBMC() {
            QRST_DI_MS_Console.CityObjService.getCSMBMCRequest inValue = new QRST_DI_MS_Console.CityObjService.getCSMBMCRequest();
            QRST_DI_MS_Console.CityObjService.getCSMBMCResponse retVal = ((QRST_DI_MS_Console.CityObjService.CityObjServicePortType)(this)).getCSMBMC(inValue);
            return retVal.@return;
        }
    }
}
