//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_TS_Process.JCGXCallBack {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jcgxws.database.com", ConfigurationName="JCGXCallBack.WS_DB_CallbackPortType")]
    public interface WS_DB_CallbackPortType {
        
        // CODEGEN: 参数“opID”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:CallBack_Down", ReplyAction="urn:CallBack_DownResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_TS_Process.JCGXCallBack.CallBack_DownResponse CallBack_Down(QRST_DI_TS_Process.JCGXCallBack.CallBack_DownRequest request);
        
        // CODEGEN: 参数“opID”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:CallBack_Up", ReplyAction="urn:CallBack_UpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_TS_Process.JCGXCallBack.CallBack_UpResponse CallBack_Up(QRST_DI_TS_Process.JCGXCallBack.CallBack_UpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallBack_Down", WrapperNamespace="http://jcgxws.database.com", IsWrapped=true)]
    public partial class CallBack_DownRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string opID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string backInfo;
        
        public CallBack_DownRequest() {
        }
        
        public CallBack_DownRequest(string opID, string backInfo) {
            this.opID = opID;
            this.backInfo = backInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallBack_DownResponse", WrapperNamespace="http://jcgxws.database.com", IsWrapped=true)]
    public partial class CallBack_DownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=0)]
        public int @return;
        
        public CallBack_DownResponse() {
        }
        
        public CallBack_DownResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallBack_Up", WrapperNamespace="http://jcgxws.database.com", IsWrapped=true)]
    public partial class CallBack_UpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string opID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string backInfo;
        
        public CallBack_UpRequest() {
        }
        
        public CallBack_UpRequest(string opID, string backInfo) {
            this.opID = opID;
            this.backInfo = backInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallBack_UpResponse", WrapperNamespace="http://jcgxws.database.com", IsWrapped=true)]
    public partial class CallBack_UpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jcgxws.database.com", Order=0)]
        public int @return;
        
        public CallBack_UpResponse() {
        }
        
        public CallBack_UpResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_DB_CallbackPortTypeChannel : QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_DB_CallbackPortTypeClient : System.ServiceModel.ClientBase<QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType>, QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType {
        
        public WS_DB_CallbackPortTypeClient() {
        }
        
        public WS_DB_CallbackPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_DB_CallbackPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_DB_CallbackPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_DB_CallbackPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_TS_Process.JCGXCallBack.CallBack_DownResponse QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType.CallBack_Down(QRST_DI_TS_Process.JCGXCallBack.CallBack_DownRequest request) {
            return base.Channel.CallBack_Down(request);
        }
        
        public int CallBack_Down(string opID, string backInfo) {
            QRST_DI_TS_Process.JCGXCallBack.CallBack_DownRequest inValue = new QRST_DI_TS_Process.JCGXCallBack.CallBack_DownRequest();
            inValue.opID = opID;
            inValue.backInfo = backInfo;
            QRST_DI_TS_Process.JCGXCallBack.CallBack_DownResponse retVal = ((QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType)(this)).CallBack_Down(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_TS_Process.JCGXCallBack.CallBack_UpResponse QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType.CallBack_Up(QRST_DI_TS_Process.JCGXCallBack.CallBack_UpRequest request) {
            return base.Channel.CallBack_Up(request);
        }
        
        public int CallBack_Up(string opID, string backInfo) {
            QRST_DI_TS_Process.JCGXCallBack.CallBack_UpRequest inValue = new QRST_DI_TS_Process.JCGXCallBack.CallBack_UpRequest();
            inValue.opID = opID;
            inValue.backInfo = backInfo;
            QRST_DI_TS_Process.JCGXCallBack.CallBack_UpResponse retVal = ((QRST_DI_TS_Process.JCGXCallBack.WS_DB_CallbackPortType)(this)).CallBack_Up(inValue);
            return retVal.@return;
        }
    }
}
