//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.WS_QDB_Searcher_Sqlite {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_QDB_Searcher_Sqlite.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSetFromSQLite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataSetFromSQLite(string sql, string DataSourcePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearTile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearTile(string[] position, int[] datetime, string[] satellite, string[] sensor, string[] datatype, string[] tileLevel, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearPRODTile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearPRODTile(string[] position, int[] datetime, string[] datatype, string[] tileLevel, int pageIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QRST_DI_MS_Console.WS_QDB_Searcher_Sqlite.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.WS_QDB_Searcher_Sqlite.ServiceSoap>, QRST_DI_MS_Console.WS_QDB_Searcher_Sqlite.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet GetDataSetFromSQLite(string sql, string DataSourcePath) {
            return base.Channel.GetDataSetFromSQLite(sql, DataSourcePath);
        }
        
        public System.Data.DataSet SearTile(string[] position, int[] datetime, string[] satellite, string[] sensor, string[] datatype, string[] tileLevel, int pageIndex) {
            return base.Channel.SearTile(position, datetime, satellite, sensor, datatype, tileLevel, pageIndex);
        }
        
        public System.Data.DataSet SearPRODTile(string[] position, int[] datetime, string[] datatype, string[] tileLevel, int pageIndex) {
            return base.Channel.SearPRODTile(position, datetime, datatype, tileLevel, pageIndex);
        }
    }
}
