//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSetFromSQLite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataSetFromSQLite(string sql, string DataSourcePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataDistinct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetDataDistinct(string distinctSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearTileSatellites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SearTileSatellites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearTileSensors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SearTileSensors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearTileLevels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SearTileLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearProTileLevels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SearProTileLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearTilePaged", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearTilePaged(out int allRecordCount, string[] position, int[] datetime, string[] satellite, string[] sensor, string[] datatype, string[] tileLevel, int startIndex, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearPRODTilePaged", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearPRODTilePaged(out int allRecordCount, string[] position, int[] datetime, string[] datatype, string[] tileLevel, int startIndex, int offset);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QRST_DI_MS_Console.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.ServiceReference1.ServiceSoap>, QRST_DI_MS_Console.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet GetDataSetFromSQLite(string sql, string DataSourcePath) {
            return base.Channel.GetDataSetFromSQLite(sql, DataSourcePath);
        }
        
        public string[] GetDataDistinct(string distinctSql) {
            return base.Channel.GetDataDistinct(distinctSql);
        }
        
        public string[] SearTileSatellites() {
            return base.Channel.SearTileSatellites();
        }
        
        public string[] SearTileSensors() {
            return base.Channel.SearTileSensors();
        }
        
        public string[] SearTileLevels() {
            return base.Channel.SearTileLevels();
        }
        
        public string[] SearProTileLevels() {
            return base.Channel.SearProTileLevels();
        }
        
        public System.Data.DataSet SearTilePaged(out int allRecordCount, string[] position, int[] datetime, string[] satellite, string[] sensor, string[] datatype, string[] tileLevel, int startIndex, int offset) {
            return base.Channel.SearTilePaged(out allRecordCount, position, datetime, satellite, sensor, datatype, tileLevel, startIndex, offset);
        }
        
        public System.Data.DataSet SearPRODTilePaged(out int allRecordCount, string[] position, int[] datetime, string[] datatype, string[] tileLevel, int startIndex, int offset) {
            return base.Channel.SearPRODTilePaged(out allRecordCount, position, datetime, datatype, tileLevel, startIndex, offset);
        }
    }
}
