//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRST_DI_MS_Console.VNorthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bp.zjugis.edu", ConfigurationName="VNorthService.VegetationNorthServicePortType")]
    public interface VegetationNorthServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getGPSJ", ReplyAction="urn:getGPSJResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.VNorthService.getGPSJResponse getGPSJ(QRST_DI_MS_Console.VNorthService.getGPSJRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getWHQ", ReplyAction="urn:getWHQResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.VNorthService.getWHQResponse getWHQ(QRST_DI_MS_Console.VNorthService.getWHQRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCLBW", ReplyAction="urn:getCLBWResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.VNorthService.getCLBWResponse getCLBW(QRST_DI_MS_Console.VNorthService.getCLBWRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTypes", ReplyAction="urn:getTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.VNorthService.getTypesResponse getTypes(QRST_DI_MS_Console.VNorthService.getTypesRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getQueryVegetations", ReplyAction="urn:getQueryVegetationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRST_DI_MS_Console.VNorthService.getQueryVegetationsResponse getQueryVegetations(QRST_DI_MS_Console.VNorthService.getQueryVegetationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJ", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fseq;
        
        public getGPSJRequest() {
        }
        
        public getGPSJRequest(string fseq) {
            this.fseq = fseq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGPSJResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getGPSJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getGPSJResponse() {
        }
        
        public getGPSJResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWHQ", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getWHQRequest {
        
        public getWHQRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWHQResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getWHQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getWHQResponse() {
        }
        
        public getWHQResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCLBW", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getCLBWRequest {
        
        public getCLBWRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCLBWResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getCLBWResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getCLBWResponse() {
        }
        
        public getCLBWResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypes", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getTypesRequest {
        
        public getTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTypesResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getTypesResponse() {
        }
        
        public getTypesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryVegetations", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryVegetationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maxLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string minLng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zbmc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zblb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clbw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagenum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pagesize;
        
        public getQueryVegetationsRequest() {
        }
        
        public getQueryVegetationsRequest(string dts, string dte, string maxLat, string maxLng, string minLat, string minLng, string zbmc, string zblb, string clbw, string whq, string pagenum, string pagesize) {
            this.dts = dts;
            this.dte = dte;
            this.maxLat = maxLat;
            this.maxLng = maxLng;
            this.minLat = minLat;
            this.minLng = minLng;
            this.zbmc = zbmc;
            this.zblb = zblb;
            this.clbw = clbw;
            this.whq = whq;
            this.pagenum = pagenum;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQueryVegetationsResponse", WrapperNamespace="http://service.bp.zjugis.edu", IsWrapped=true)]
    public partial class getQueryVegetationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bp.zjugis.edu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getQueryVegetationsResponse() {
        }
        
        public getQueryVegetationsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VegetationNorthServicePortTypeChannel : QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VegetationNorthServicePortTypeClient : System.ServiceModel.ClientBase<QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType>, QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType {
        
        public VegetationNorthServicePortTypeClient() {
        }
        
        public VegetationNorthServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VegetationNorthServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VegetationNorthServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VegetationNorthServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.VNorthService.getGPSJResponse QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType.getGPSJ(QRST_DI_MS_Console.VNorthService.getGPSJRequest request) {
            return base.Channel.getGPSJ(request);
        }
        
        public string getGPSJ(string fseq) {
            QRST_DI_MS_Console.VNorthService.getGPSJRequest inValue = new QRST_DI_MS_Console.VNorthService.getGPSJRequest();
            inValue.fseq = fseq;
            QRST_DI_MS_Console.VNorthService.getGPSJResponse retVal = ((QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType)(this)).getGPSJ(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.VNorthService.getWHQResponse QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType.getWHQ(QRST_DI_MS_Console.VNorthService.getWHQRequest request) {
            return base.Channel.getWHQ(request);
        }
        
        public string getWHQ() {
            QRST_DI_MS_Console.VNorthService.getWHQRequest inValue = new QRST_DI_MS_Console.VNorthService.getWHQRequest();
            QRST_DI_MS_Console.VNorthService.getWHQResponse retVal = ((QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType)(this)).getWHQ(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.VNorthService.getCLBWResponse QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType.getCLBW(QRST_DI_MS_Console.VNorthService.getCLBWRequest request) {
            return base.Channel.getCLBW(request);
        }
        
        public string getCLBW() {
            QRST_DI_MS_Console.VNorthService.getCLBWRequest inValue = new QRST_DI_MS_Console.VNorthService.getCLBWRequest();
            QRST_DI_MS_Console.VNorthService.getCLBWResponse retVal = ((QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType)(this)).getCLBW(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.VNorthService.getTypesResponse QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType.getTypes(QRST_DI_MS_Console.VNorthService.getTypesRequest request) {
            return base.Channel.getTypes(request);
        }
        
        public string getTypes() {
            QRST_DI_MS_Console.VNorthService.getTypesRequest inValue = new QRST_DI_MS_Console.VNorthService.getTypesRequest();
            QRST_DI_MS_Console.VNorthService.getTypesResponse retVal = ((QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType)(this)).getTypes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRST_DI_MS_Console.VNorthService.getQueryVegetationsResponse QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType.getQueryVegetations(QRST_DI_MS_Console.VNorthService.getQueryVegetationsRequest request) {
            return base.Channel.getQueryVegetations(request);
        }
        
        public string getQueryVegetations(string dts, string dte, string maxLat, string maxLng, string minLat, string minLng, string zbmc, string zblb, string clbw, string whq, string pagenum, string pagesize) {
            QRST_DI_MS_Console.VNorthService.getQueryVegetationsRequest inValue = new QRST_DI_MS_Console.VNorthService.getQueryVegetationsRequest();
            inValue.dts = dts;
            inValue.dte = dte;
            inValue.maxLat = maxLat;
            inValue.maxLng = maxLng;
            inValue.minLat = minLat;
            inValue.minLng = minLng;
            inValue.zbmc = zbmc;
            inValue.zblb = zblb;
            inValue.clbw = clbw;
            inValue.whq = whq;
            inValue.pagenum = pagenum;
            inValue.pagesize = pagesize;
            QRST_DI_MS_Console.VNorthService.getQueryVegetationsResponse retVal = ((QRST_DI_MS_Console.VNorthService.VegetationNorthServicePortType)(this)).getQueryVegetations(inValue);
            return retVal.@return;
        }
    }
}
